name: Print File Workflow

on:
  push:
    branches:
      - dev
      - uat  # Runs on PR creation or update

 # push:
  #  branches:
  #    - dev
  #    - uat  # Runs when a PR is merged or direct push happens

jobs:
  print_file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # This is required to fetch your files

      - name: Print hello.txt Contents
        run: ls
        run: cat hello.txt
