name: PR Closed Workflow

on:
  pull_request:
    branches:
      - dev
      - uat
    types:
      - closed

jobs:
  pr-closed:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run some tasks
        run: |
          echo "Pull request to dev branch has been closed!"
